# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np

Z = np.random.random((3,3,3))
print(Z)

[[[0.85693529 0.9483678  0.4373462 ]
  [0.4918579  0.85776609 0.10580163]
  [0.43482488 0.30019969 0.7914588 ]]

 [[0.17684923 0.09247569 0.25701632]
  [0.44931059 0.66227757 0.51264467]
  [0.7567477  0.35496079 0.80789423]]

 [[0.2001008  0.74832471 0.75205786]
  [0.87605288 0.22728355 0.84318735]
  [0.34935116 0.23726648 0.8102178 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.42726848  1.54950385 -0.29268262  0.92177536  0.13566021]
 [ 0.01512028 -0.9195461   0.54475174  0.98630683 -0.50658731]
 [ 0.81804631  0.80120189 -0.39349021  1.28632057  1.51107506]
 [-0.41095131 -1.35511411 -0.53140181 -0.91273695  0.91474263]
 [-1.62308781 -0.0420193  -1.55236206 -1.27573741 -1.09605621]]


# 5.  How to find common values between two arrays?

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-02
2020-08-03
2020-08-04


# 7. Consider two random array A and B, check if they are equal

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.72545836 0.56647604 0.68065561 0.         0.29619157 0.18129171
 0.61837952 0.56408997 0.43756869 0.21135211]


# 9. How to print all the values of an array?

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-0.01987987  0.449612   -0.38531786  0.08476653 -0.04619444  0.09789897
  -0.13394021  0.0802111  -0.32286112  0.19570491]
 [-0.46059205 -0.04355294  0.16631734 -0.08125329  0.08208396  0.33091127
   0.46228859 -0.36120051 -0.1642834   0.06928103]
 [-0.06504358  0.01478068 -0.00429045  0.287582    0.28590688 -0.33633012
   0.06531203  0.09968583 -0.14388482 -0.20371844]
 [-0.37643952  0.35405063  0.31048816 -0.1999694  -0.1543467   0.15434449
   0.2287735  -0.56243082  0.32933883 -0.08380918]
 [-0.07457285 -0.41351836  0.4175285   0.22699289  0.31774564 -0.34730869
  -0.32904306 -0.18094367 -0.03999495  0.42311457]]
[[-0.01987987  0.449612   -0.38531786  0.08476653 -0.04619444  0.09789897
  -0.13394021  0.0802111  -0.32286112  0.19570491]
 [-0.46059205 -0.04355294  0.16631734 -0.08125329  0.08208396  0.33091127
   0.46228859 -0.36120051 -0.1642834   0.06928103]
 [-0.06504358  0.01478068 -0.00429045  0.287582    0.28590688 -0.33633012
   0.06531203  0.09968583 -0.14388482 -0.20371844]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 4. 2. 3. 2. 4. 1. 4. 3.]


In [ ]:
np.add.at(Z, I, 1)
print(Z)

[7. 3. 3. 7. 7. 5. 1. 7. 3. 7.]


# 12.How to get the diagonal of a dot product?

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.1640444  0.12423543 0.87526535 0.69834128 0.63841149]
 [0.83405799 0.64648148 0.53638532 0.07705731 0.42121982]
 [0.66010691 0.99920648 0.06059208 0.67309661 0.45985186]
 [0.64468264 0.43711128 0.23421925 0.79680033 0.17254471]
 [0.81541808 0.92156266 0.46543321 0.3693672  0.38746696]]
[[0.346074   0.25321798 0.81797213 0.43123093 0.31701728]
 [0.5046558  0.29396973 0.66455112 0.21907234 0.06838471]
 [0.70906319 0.2501509  0.17097672 0.64303846 0.98934129]
 [0.60804729 0.94629905 0.21055505 0.65608309 0.99010739]
 [0.78830691 0.66397381 0.98363051 0.54882069 0.82193898]]
diagonal of a dot product method 1 is.... [1.66797479 0.88801992 1.80838089 1.1418414  1.4661821 ]
diagonal of a dot product method 2 is.... [1.66797479 0.88801992 1.80838089 1.1418414  1.4661821 ]


# 13.How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[8 4 7 8 1 3 6 2 5 2 2 1 1 6 6 9 8 2 8 4 9 1 5 2 7 9 5 1 5 1 3 7 9 4 6 3 7
 4 6 5 0 7 8 6 9 6 7 9 4 6]
6


# 14.How to get the n largest values of an array

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
